In [1]:
import numpy as np

In [4]:
arr=np.array([10,20,30,40])
print(arr)
#numpy array, the elements are not comma separated
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [7]:
#you can also create a multi dimensional array (like matrix)
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
#but make sure each row has same number of elements
#example-
arr=np.array([[1,2,3],[4,5]]) #will show error
print(arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [12]:
#SLICING
#used to get the specific elements
arr=np.array([1,2,3,4])
print(arr[0:3]) #will return elements of indices 0,1,2
print(arr[0:]) #will return elements from index 0 onwards to all the indices
print(arr[2:]) #will return elements from index 3 onwards
#you can also specify the ending point till which you want to return all the elements
print(arr[:3]) #will print elements of index 0,1,2

[1 2 3]
[1 2 3 4]
[3 4]
[1 2 3]


In [18]:
#SLICING IN MULTI-DIMENSIONAL ARRAYS
#example-
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0:2,0:2]) #specify which elements you want from each array-row

# in above array we want the the first 2 elements from both arrays
print(arr[0:2,0:3]) #from both arrays 3 elements will be returned (arrays should be equal)

#if you want specific elements from a specific array
print(arr[0,1:4]) #from the zeroth(first) array you want elements from indices 1 to 3
print(arr[1,2]) #from the second array you want to print index 2 value

[[10 20]
 [50 60]]
[[10 20 30]
 [50 60 70]]
[20 30 40]
70


In [27]:
#ATTRIBUTES
arr=np.array([[10,20,30,40],[50,60,60,80]])
print(arr)
print(" ")
#to get the shape of the matrix (no. of rows and columns)
print(np.shape(arr)) # (2,4) -> 2 rows and 4 columns

#to get the total number of elements in the array
print(np.size(arr)) # 2*4 -> 8 elements

#to get the number of dimensions of the matrix
print(np.ndim(arr)) #matrix has rows and columns -> 2D matrix

#to get the datatype of the elements in the matrix
print(arr.dtype) #the elements are integers -> int64

[[10 20 30 40]
 [50 60 60 80]]
 
(2, 4)
8
2
int64


In [39]:
#INSPECTING AN ARRAY
a=[30,40,20,40,30]
arr=np.array(a) #you can make a list and then pass that to create numpy array
print(arr)
#to get the shape of the matrix (no. of rows and columns)
print(arr.shape) #(5,) -> 5 rows, 0 cols

#to get the number of nested values
print(len(arr))

#to get the number of elements in the array
print(arr.size) #no. of elements in the array

#to get the datatype of array
print(type(arr)) #this is a numpy array

#to get the datatype of elements in the array
print(arr.dtype)

#to change the datatype of the element
print(arr.astype(float)) #the datatype is converted to float
print(arr.astype(str)) #datatype is converted to string


[30 40 20 40 30]
(5,)
5
5
<class 'numpy.ndarray'>
int64
[30. 40. 20. 40. 30.]
['30' '40' '20' '40' '30']


In [49]:
#MATHEMATICAL OPRATIONS AND FUNCTIONS ON ARRAYS
#consider the arrays 
arr1=np.array([30,40,60,20,10])
arr2=np.array([30,20,10,20,20])
print(" ")

#to print the addition of arrays
print(arr1+arr2)
#alternative way is to use np.add
print(np.add(arr1,arr2))
print(" ")

#to print the subtraction of arrays
print(arr1-arr2)
#alternative way is to use np.subtract
print(np.subtract(arr1,arr2))
print(" ")

#to print the multiplication of arrays
print(arr1*arr2)
#alternative way is to use np.multiply
print(np.multiply(arr1,arr2))
print(" ")

#to print the division of arrays
print(arr1/arr2)
#alternative way is to use np.divide
print(np.divide(arr1,arr2))
print(" ")

#to convert elements to their power of another number
arr1=([1,2,3,4])
arr2=np.array([3])
print(np.power(arr1,arr2)) #arr1 elements are raised to the power of element in arr2
print(" ")

#to find the square-root of elements
arr1=np.array([27,64,4,9])
print(np.sqrt(arr1))

 
[60 60 70 40 30]
[60 60 70 40 30]
 
[  0  20  50   0 -10]
[  0  20  50   0 -10]
 
[900 800 600 400 200]
[900 800 600 400 200]
 
[1.  2.  6.  1.  0.5]
[1.  2.  6.  1.  0.5]
 
[ 1  8 27 64]
 
[5.19615242 8.         2.         3.        ]


In [52]:
#COMBINING AND SPLITTING ARRAYS
#to concatinate arrays in numpy we cannot simply use '+' operator
#'+' operator will denote mathematical addition in NUMPY
#instead np.concatenate is used

arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(np.concatenate([arr1,arr2]))

[1 2 3 4 5 6 7 8]


In [57]:
#in numpy there are 2 axes (horizontal and vertical)
#axis=0 refers to horizontal concatination
#axis=1 refers to vertical concatination

arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[5,6,7,8],[1,2,3,4]])
print(np.concatenate(([arr1,arr2]),axis=0))
print(" ")
print(np.concatenate(([arr1,arr2]),axis=1))


[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]
 
[[1 2 3 4 5 6 7 8]
 [5 6 7 8 1 2 3 4]]


In [60]:
#another method to do horizontal concatenation stack is by using np.hstack
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[5,6,7,8],[1,2,3,4]])
print(np.hstack([arr1,arr2]))
print(" ")

#another method to do vertical concatenation stack is by using np.vstack
print(np.vstack([arr1,arr2]))

[[1 2 3 4 5 6 7 8]
 [5 6 7 8 1 2 3 4]]
 
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


In [64]:
#to split an array into a given number use np.array_split
a=np.array([1,2,3,4,5,6])
print(np.array_split(a,3)) #argument is the np.array and the number of splits we want


[array([1, 2]), array([3, 4]), array([5, 6])]


In [72]:
#ADDING AND REMOVING ELEMENTS IN ARRAYS
#np.append() - appends items to array
#np.insert() - inserts items into an array
#np.delete() - deletes items from array

a=np.array([20,30,40,50])
#to append element
print(np.append(a,90))
#if we want to append to 2-D matrix
a=np.array([[1,2,3],[4,5,6]])
print(np.append(a,78)) #first the 2-D matrix is converted to a 1-D array then the element is appended
print(" ") #array,value

#to insert element
#suppose we want to insert 50 at the 1th index
a=np.array([1,2,3,4,5])
print(np.insert(a,1,50)) #array,index,value
print(" ")

#to delete element
a=np.array([1,2,3,4,5])
print(np.delete(a,3)) #array,index

[20 30 40 50 90]
[ 1  2  3  4  5  6 78]
 
[ 1 50  2  3  4  5]
 
[1 2 3 5]


In [79]:
#NUMPY SORT, FILTER & SEARCH
arr=np.array([1,3,3,0])
#to sort the arrayv use np.sort
print(np.sort(arr))
print(" ")

#to search for an element use np.where
arr=np.array([1,5,3,0])
s=np.where(arr==5) #enter the element you want to search for 
print(s) #this will print the index of that element we are searching for

#example - we want to find those elements which are even
s=np.where(arr%2==0)
print(s)
print(" ") 

#to search for an element in a sorted array use np.searchsorted
arr=np.array([0,1,5,6,10])
ss=np.searchsorted(arr,5) #array,element we want to search
print(ss)
print(" ")

#filter


[0 1 3 3]
 
(array([1]),)
(array([3]),)
 
2
 


In [88]:
#AGGREGATING FUNCTIONS IN ARRAYS
arr=np.array([20,40,60,70])

#to find sum of the elements
print(np.sum(arr))
print(" ")

#to find the min value in array
print(np.min(arr))
print(" ")

#to find the max value in array
print(np.max(arr))
print(" ")

#to find mean of all elements
print(np.mean(arr))
print(" ")

#to find the cumulative sum
print(np.cumsum(arr)) #step-wise addition
print(" ")

#to find the cumulative product
print(np.cumprod(arr)) #step-wise multiplication
print(" ")

190
 
20
 
70
 
47.5
 
[ 20  60 120 190]
 
[     20     800   48000 3360000]
 


In [97]:
#STATISTICAL FUNCTIONS IN NUMPY
import statistics as stats
#example - 
baked_food = [200,300,150,130,200,170]
a=np.array(baked_food)
print(np.mean(a)) #to get mean of the values (sum of all values/number of values)
print(" ")

print(np.median(a)) #to get median value (central value after sorting)
print(" ")

print(stats.mode(a)) #mode function will come uder statistics library
print(" ")

print(np.std(a)) #to get the standard deviation (tell us by how much values differ by mean value)
print(" ")

print(np.var(a)) #variance = (standard deviation)^2

191.66666666666666
 
185.0
 
200
 
54.594464513864004
 
2980.555555555556


In [99]:
#example -
tobacco_consumption=[30,50,10,30,50,40]
deaths=[100,120,70,100,120,112]

print(np.corrcoef([tobacco_consumption,deaths])) #to get the correlation coeeficient

#correlation coeefeicient lies between -1 to +1
# -1 represents inversly proportional relationship
# 1 represents proportional relationship
# 0 means no relationship

[[1.         0.99015454]
 [0.99015454 1.        ]]
