## Numpy

## converting a list to an array

In [1]:
import numpy as np

list_example = [12,45,23,78]

array = np.array(list_example)
array

array([12, 45, 23, 78])

## checking the datatype using type function

In [2]:
type(array)

numpy.ndarray

## mathematical operations can be applied on arrays
   addition of lists give concatenation while addition of arrays give addition

In [3]:
array*2.54

array([ 30.48, 114.3 ,  58.42, 198.12])

In [4]:
# addition operation

#list concatenates
list1 = [1,2,3]
list2 = [4,5,6]
print(list1 + list2)

#array performs addition
array1 = np.array(list1)
array2 = np.array(list2)
print(array1 + array2)

[1, 2, 3, 4, 5, 6]
[5 7 9]


## shape, dimension and datatype

In [5]:
# tuple that contains weight and height of players - 
players = [(63,169), (70,189), (86,180), (45,130)]
print(players[2][1])
print(len(players))

array = np.array(players)
print(array)
print(array.shape) # output = (4,2) - 4 rows and 2 columns.

# dimension of the array
print(array.ndim) # output - 2

# datatype of elements in the array
print(array.dtype)

180
4
[[ 63 169]
 [ 70 189]
 [ 86 180]
 [ 45 130]]
(4, 2)
2
int32


## multiplication of 2D arrays

In [6]:
# multiplying the first column with 3 and second column with 2

multiplied_array = array * [3,2]
print(multiplied_array)

[[189 338]
 [210 378]
 [258 360]
 [135 260]]


## accessing elements of arrays

In [7]:
# accessing the first row
print(array[0])

# accessing the second element of the first row
print(array[0][1])

# accessing the first column
print(array[:,0])

[ 63 169]
169
[63 70 86 45]


In [8]:
# fetching the players who have height greater than 170
new_array = array[:,1] > 170 # this creates a boolean array marking true for all the values satifying the condition and false otherwise.
print(new_array)

new_array1 = array[array[:,1] > 170] # fetches the values which are true in the previous step
print(new_array1)

print(new_array1.shape)

[False  True  True False]
[[ 70 189]
 [ 86 180]]
(2, 2)


In [9]:
skill = ['batsman', 'bowler', 'batsman','bowler']
skill_array = np.array(skill) # size of the skill_array and the 'array' array should be same because we will be applying operations on them together
print(skill_array)
# fetch the height of all players who are batsman
batsman_array = array[skill_array == 'batsman']
print(batsman_array)

['batsman' 'bowler' 'batsman' 'bowler']
[[ 63 169]
 [ 86 180]]


## help function

In [10]:
# use help function whenever you are stuck anywhere, it tells the use of the function you mention in it 
help(np.ones) # tells what does the np.ones function does

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionad

## creating a 1D array

In [11]:
# creating a 1D array with all 1s 
arr = np.ones(5)
print(arr)

print(arr.dtype) # output - float, by default the array created is of float type so if you want the array to be of some other datatype 
                          # you have to mention it explicitly

arr_int = np.ones(6,dtype = int)
print(arr_int)

# creating a 2D array
arr_2d = np.ones((6,4))
print('2d array - ')
print(arr_2d)

[1. 1. 1. 1. 1.]
float64
[1 1 1 1 1 1]
2d array - 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
# creating a 1D array with all 0s. Everything is same just the function is different.

arr = np.zeros(5)
print(arr)

arr_int = np.zeros(6,dtype = int)
print(arr_int)


[0. 0. 0. 0. 0.]
[0 0 0 0 0 0]


## creating a list

In [13]:
# create a list from a range L to R-1
list(range(1,5)) # creates a list from 1 to 4

[1, 2, 3, 4]

## creating an array using arange function

In [14]:
# create an array from range 0 to n-1
array3 = np.arange(5)
print(array3)

# np.arange(start, end(not included), step size)
array4 = np.arange(4,10,2)
print(array4)

[0 1 2 3 4]
[4 6 8]


## random function

In [15]:
# random function 1D array
# create an array using integers in the range L to R(not included)
array1 = np.random.randint(5,size = 10) # creates an array using integers in the range 0 to 5(not included) of size = 10
print(array1)

# create an array using integers in the range L to R(not included)
array2 = np.random.randint(3,6,size = 10) # creates an array using integers from 3 to 6(not included) of size = 10
print(array2)

[1 0 3 3 4 4 3 3 3 2]
[4 3 3 3 3 5 4 5 4 5]


In [16]:
# random function 2D array
np.random.random([3,4]) # 3 is the number of rows and 4 is the number of columns

array([[0.08591892, 0.85808647, 0.65943059, 0.91313623],
       [0.43579853, 0.86974801, 0.35852016, 0.59842332],
       [0.50311744, 0.67102536, 0.78244387, 0.88897655]])

## Note - the shape and dimension of the arrays should be same to apply the operation


## Stacking Arrays

In [17]:
# Stacking arrays

#hstack()-horizontal stack
#vstack()-vertical stack
a = np.array([1,2,3])
b = np.array([2,3,4])
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [18]:
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [19]:
array5 = np.arange(12).reshape(3,4) # 3*4
array6 = np.arange(20).reshape(5,4) # 5*4

np.vstack((array5,array6))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## power function

In [20]:
# power function for exponential operation
np.power(array5,2) # power 2 of all the elements of array5

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

## absolute function

In [21]:
# converting a negetive array into positive using abs or absolute function
neg_array = np.array([-1,-4,3,0,-66])

print(abs(neg_array))
# or
print(np.absolute(neg_array))

[ 1  4  3  0 66]
[ 1  4  3  0 66]
